name: reproduction
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=10

    steps:
      - uses: actions/checkout@v2
      - name: test localhost
        continue-on-error: true
        run: mysql --user root -proot --host localhost --port 3306 --database test -e "SELECT 1"
      - name: test 127.0.0.1
        continue-on-error: true
        run: mysql --user root -proot --host 127.0.0.1 --port 3306 --database test -e "SELECT 1"
      - name: test ::1
        continue-on-error: true
        run: mysql --user root -proot --host ::1 --port 3306 --database test -e "SELECT 1"
