name: reproduction
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
      - uses: actions/checkout@v2
      - name: test localhost
        continue-on-error: true
        run: mysql --user root -ppassword --host localhost --port 32574 --database test -e "SELECT 1"
      - name: test 127.0.0.1
        continue-on-error: true
        run: mysql --user root -ppassword --host 127.0.0.1 --port 32574 --database test -e "SELECT 1"
      - name: test ::1
        continue-on-error: true
        run: mysql --user root -ppassword --host ::1 --port 32574 --database test -e "SELECT 1"
